site_name: Terraform Remote State S3 Backend
site_description: 'Documentation for the Terraform Remote State S3 Backend'
site_author: 'Stefan Freitag'
docs_dir: docs/
repo_name: 'stefanfreitag/terraform-backend-s3-bucket'
repo_url: 'https://github.com/stefanfreitag/terraform-backend-s3-bucket'
edit_uri: blob/main/docs/
nav:
    - Home: index.md
    - Features: features.md
    - Links: links.md
theme:
  name: 'material'
  palette:
    scheme: default

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences